### ISSUE TITLE
unit

### ISSUE THREAD

**Issue by hosseinrezaa** [InteractiveComputerGraphics/SPlisHSPlasH#110]
Hi
What are the units of viscosity, surface tension, and force?

**Comment by janbender** [comment]
This depends on the individual method. 

For the viscosity methods Standard, Takahashi and Weiler the dynamic viscosity coefficient is used with the unit  N·s/m^2:
https://en.wikipedia.org/wiki/Viscosity#Units

For the surface tension methods you have to take a look at the corresponding papers since all use different coefficients.

**Comment by hosseinrezaa** [comment]
I am using XSPH method.

**Comment by janbender** [comment]
XSPH is not a real viscosity method. It smoothes the velocity field which looks like viscous behavior but the parameter is not physically meaningful. 

I would recommend to use the standard viscosity which uses the dynamic viscosity parameter.
