### ISSUE TITLE
Question about the input fluid model

### ISSUE THREAD

**Issue by hongshul** [InteractiveComputerGraphics/SPlisHSPlasH#15]
Hi,
 I meet a question how to get or generate the inputfile of the **_bgeo_** fluid model.

 I had searched "bgeo" on the Internet, and found it may be the file of houdini. Then I dowmload the newest houdini and generate a bgeo file. But the SPlisHSPlasH project read nothing form it.
Cheers

**Comment by janbender** [comment]
Hi, 

probably I should update the partio library since it seems that it cannot read the newest format. 
However, we have two tools in SPlisHSPlasH that you can use. VolumeSampling generates a volumetric sampling (as bgeo) for an OBJ. This can be used as fluid. SurfaceSampling generates a bgeo for the surface of a OBJ mesh which can be used as boundary. 

Hope that helps, 

Jan

**Comment by hongshul** [comment]
Thanks for the answer!
