### ISSUE TITLE
Simulation takes a long time to run

### ISSUE THREAD

**Issue by ManosAgelidis** [InteractiveComputerGraphics/SPlisHSPlasH#33]
Hello, I am running a simulation with the following .json 

```
{
	"Configuration": 
	{
		"timeStepSize": 0.001,
		"numberOfStepsPerRenderUpdate": 2,
		"particleRadius": 0.005, 
		"density0": 1000, 
		"simulationMethod": 3,
		"gravitation": [0,-9.81,0], 
		"cflMethod": 0, 
		"cflFactor": 1,
		"cflMaxTimeStepSize": 0.005,
		"maxIterations": 100,
		"maxError": 0.01,
		"maxIterationsV": 100,
		"maxErrorV": 0.1,		
		"stiffness": 50000,
		"exponent": 7,
		"velocityUpdateMethod": 0,
		"enableDivergenceSolver": true
	},

	"RigidBodies": [
		{
			"geometryFile": "../models/UnitBox1.obj",
			"translation": [0,0.25,0],
			"rotationAxis": [1, 0, 0],
			"rotationAngle": 0,
			"scale": [0.5, 0.5, 0.5],
			"color": [0.5, 0.5, 0.5, 1.0], 
			"isDynamic": false,
			"restitution" : 0.6,
			"friction" : 0.0,
			"collisionObjectType": 2,
			"collisionObjectScale": [0.5, 0.5, 0.5],	
			"isWall": true,
			"invertSDF": true
		}
	],
	"FluidBlocks": [
		{
			"denseMode": 0,
			"start": [ -0.25,0.0, -0.25],
			"end": [ 0.25, 0.5,0.25]
		}
	]

}
```

By replacing the DoubleDamBreak.json with this one and running the StaticBoundaryDemo. I let it run for 20 hours with 8 mpi cores, and it only simulated 0.43 seconds. The output from the run:

```
./bin/StaticBoundaryDemo
Load scene file: /home/manos/Dev/SPlisHSPlasH/data/Scenes/DoubleDamBreakWithSphere.json
OpenGL version 4.6
Using GLEW 1.12.0
Vendor: NVIDIA Corporation
Renderer: GeForce GT 730M/PCIe/SSE2
Version: 4.6.0 NVIDIA 396.54
Initialize fluid particles
Number of fluid particles: 117649
Loading /home/manos/Dev/SPlisHSPlasH/data/models/UnitBox1.obj
Number of triangles: 10
Number of vertices: 8
Loaded cached boundary sampling: /home/manos/Dev/SPlisHSPlasH/data/Scenes/Cache/UnitBox1_sbd_0.005000_0.500000_0.500000_0.500000.bgeo
Initialize boundary psi
Number of boundary particles: 30790
Initialize boundary psi
---------------------------------------------------------------------------

Initialize boundary psi
Average time SimStep: 142832 ms
Average time pressureSolve: 123316 ms
Average time predictAdvection: 10080.7 ms
Average time neighborhood_search: 407.426 ms
Average time computeNonPressureForces: 4648.83 ms
---------------------------------------------------------------------------

Time sum SimStep: 7.88435e+07 ms
Time sum pressureSolve: 6.80704e+07 ms
Time sum predictAdvection: 5.56457e+06 ms
Time sum neighborhood_search: 224899 ms
Time sum computeNonPressureForces: 2.56616e+06 ms
---------------------------------------------------------------------------

---------------------------------------------------------------------------

---------------------------------------------------------------------------

Sum of emitted particles: 0
Sum of reused particles: 0
```

It seems a bit weird that the timing calculations are done twice, and it takes super long to complete just 0.43 secs of simulation. I am trying to simulate a pool of water with resting particles. Am I doing something wrong or is this normal behaviour?

Best,
Manos

**Comment by janbender** [comment]
I tried this scenario but I didn't have the geometry UnitBox1.obj so I used the UnitBox.obj of SPlisHSPlasH. 

The problem of this scenario is that you have a high stack of particles. At the same time almost nothing happens. In this case the CFL condition decides to use large time steps. However, solving a high stack with large time steps is not a good idea since a large number of iterations is required which makes the simulation slow. Probably even the maximum number of iterations is not enough and some particles will slip through the boundary. These particles will then dominate the CFL condition and lead to the lowest possible time step. In summary the simulation will be very slow. 

You could try to use a fixed time step size or the CFL-method "CFL - iterations" and a CFL factor of 0.5. This CFL method reduces the time step if too many iterations are required since the largest time step does not lead to the fastest simulation.

**Comment by ManosAgelidis** [comment]
Great answer, thanks a lot! I was suspecting that it had to do with the CFL condition, but was unsure how to fix it. For the record the UnitBox1.obj is just a box with the top surface missing. Thanks again!
