### ISSUE TITLE
Can this work on Unity ?

### ISSUE THREAD

**Issue by nvcken** [InteractiveComputerGraphics/SPlisHSPlasH#35]

**Comment by cesss** [comment]
I don't see any reason why it couldn't work on Unity (but note that fluids simulation is compute-intensive, so if you are thinking in this for a game, consider that you'll need to properly balance the number of particles vs the framerate you wish vs the hardware power of your end users). Also, you also need to have the knowledge for writing the C++ glue code for connecting Unity to SPlisHSPlasH (unless somebody already did that task, which I don't know). I believe the Unity community would be the best place for answering this question, because SPlisHSPlasH can in theory be connected to any engine and any framework.

**Comment by cesss** [comment]
BTW, adding to my comment: if you are thinking in SPlisHSPlasH after seeing the videos, take into consideration that the results from the videos are not directly achievable at this time, because the foam generator is not in the repository yet (they are working on it at the moment), and because there's no mesh reconstructor currently available (but you should be able to find particle meshers anyway).

**Comment by janbender** [comment]
SPlisHSPlasH provides the possibility to simulate fluid particles. So to integrate this in Unity you have to write a kind of wrapper visualize things in Unity and maybe you even want to generate the scenes there. 

Doing such a project would be very nice for the community. Unfortunately, we don't have enough time for that. 

Btw. foam generation will come soon, as well as a GPU neighborhood search.

**Comment by nvcken** [comment]
Sound good, thanks
btw, Does any these generated videos in README have open source repo ?

**Comment by janbender** [comment]
I don't understand the question. The videos are generated using SPlisHSPlasH.

**Comment by nvcken** [comment]
yes, the vidoes are generated using SPlisHSPlasH, but have any of them fully public source or downloadable ( include script, 3d model .... )

**Comment by janbender** [comment]
The scene files are not included in the repo. But it is simple to write own scene files.
