### ISSUE TITLE
Option to build libraries as shared and not static

### ISSUE THREAD

**Issue by ManosAgelidis** [InteractiveComputerGraphics/SPlisHSPlasH#48]
Hello, 

I have been using SPlisHSPlasH with a robotics simulator (gazebo), and the way that the two codes are linked is through gazebo plugins which are plugged into gazebo as dynamically loaded libraries. However all the SPlisHSPlasH related libraries are compiled as static libraries, which prevents any external code that uses SPlisHSPlasH to be compiled as a shared library. The solution would be to add a cmake option to give users the option to choose the output of the compilation to be either shared or static libraries. I have tested the compilation as shared libraries and it works in linux, I would suppose that it works for other OSs as it would just change the add_library options in cmake. If you think that this would be a useful addition I could raise a PR about it.

Best,
Manos

**Comment by janbender** [comment]
Yes, I think that would be also interesting for other users. Please send me a PR and then I can also test it on Linux.

**Comment by ManosAgelidis** [comment]
Ok, thanks, I am on it.

**Comment by cesss** [comment]
It would be also very helpful if SPlisHSPlasH (and all the dependance libraries it builds recursively) could be properly installed (with "make install") in a destination directory of your choice (with a configurable prefix install dir), so that you could easily use all these libs from other applications. In the current status, when you invoke "make install", you don't get a proper installation of everything in the destination install dir.

**Comment by janbender** [comment]
That is a good point. I will put this on my ToDo list.

**Comment by kyletreece** [comment]
Hi @janbender @ManosAgelidis , was this cmake option for compiling as shared libraries ever implemented? I would also like to link SPlisHSPlasH with another repository that requires dynamic libraries.

**Comment by digitalillusions** [comment]
For Windows this is not implemented AFAIK, since you need to manually annotate the symbols that should be visible (or something like that). For Linux it should be as simple as changing the CMake `add_library` command to be shared instead of static.

If you want to use it as a shared library for some other project though, I assume you are going to wrap the functionality anyway? In that case why not make a dynamic wrapper library which links against the static SPlisHSPlasH library and exposes only the functionality you need?

**Comment by kyletreece** [comment]
Hi @digitalillusions , thank you for your response! I'm admittedly not super familiar with cmake, so I apologize if this is a naïve question. For changing the "add_library" command to specify shared, should this be done for every CMakeLists.txt file or just the main packages? I saw that some are specified as "INTERFACE" libraries, should those be changed to shared in this case?

I may end up going the route you mentioned in the second part of your response, but wanted to at least investigate a shared library approach instead to see how it works and learn a bit more about working with cmake.
