### ISSUE TITLE
Some questions regarding the Akinci Boundary Handling Method

### ISSUE THREAD

**Issue by GUT2060** [InteractiveComputerGraphics/SPlisHSPlasH#72]
Hello ! , 
From the tutorial https://animation.rwth-aachen.de/media/papers/64/2019-EG-SPH_Tutorial.pdf 

If i'm not wrong, the Akinci Boundary Handling method is described in section : 
 5.1 / One layer of non-uniform boundary samples . 
equation (95) is presenting the pressure force computation , where a correcting coefficient is used,
"gamma 2" : equation (96)   ( i think that there is a missing minus sign in equation (96) ) 

Under the present WCSPH implementation :
 1-  i can't find where this coefficient is used for the pressure computation using the Akinci boundary handling method , is that formulation of the pressure force not used ? if yes, is there a reason why not ?

2- If i got it right , in the present implementation of this boundary handling method the pressure is not precisely mirrored since: 
ai -=mj*( pi / (densityi*densityi) + pj/(density0*density0) )* gradW   (TimeStepWCSPH.cpp , line 186) i'd like to know :
why not use  2*pi/(densityi*densityi) instead of pi / (densityi*densityi) + pj/(density0*density0) ?   

Thank you kindly for your clarifications
 Best regards

**Comment by janbender** [comment]
> If i'm not wrong, the Akinci Boundary Handling method is described in section :
5.1 / One layer of non-uniform boundary samples .
equation (95) is presenting the pressure force computation , where a correcting coefficient is used,
"gamma 2" : equation (96) ( i think that there is a missing minus sign in equation (96) )

I see no reason why this term should be negative. Can you explain why you think the equation is wrong?

> Under the present WCSPH implementation :
1- i can't find where this coefficient is used for the pressure computation using the Akinci boundary handling method , is that formulation of the pressure force not used ? if yes, is there a reason why not ?

SPlisHSPlasH implements the original paper of Akinci et al. "Versatile Rigid-Fluid Coupling for Incompressible SPH" where no gamma1 or gamma2 is used. The group of Universtiy Freiburg introduced these parameters in their pressure boundaries extension. This extension is not implemented since we developed volume maps, an implicit boundary representation, which allows for more accurate results.

> 2- If i got it right , in the present implementation of this boundary handling method the pressure is not precisely mirrored since:
ai -=mj*( pi / (densityidensityi) + pj/(density0density0) )* gradW (TimeStepWCSPH.cpp , line 186) i'd like to know :
why not use 2pi/(densityidensityi) instead of pi / (densityidensityi) + pj/(density0density0) ?

This is a small improvement in our code. By deriving the equations in a constraint form, we can find a factor where pressure mirroring is not required anymore. Instead of getting a local approximation at the boundary, we now get a locally exact result. However, it is hard to decribe the whole formulas here.

**Comment by GUT2060** [comment]
Hi M bender , thank you for your responses , 

> I see no reason why this term should be negative. Can you explain why you think the equation is 
wrong?

from the comment right after equation (96) , the same factor "gamma2"  was also derived in section 5.1 / One layer of uniform boundary samples . which means that since the (96) was previously derived in equation (92) using (91) , if you derive "gamma 2" using equation (91) , isn't (96)  negative ? if that's the case then both (92) and (96) are missing a minus sign . 

> SPlisHSPlasH implements the original paper of Akinci et al. "Versatile Rigid-Fluid Coupling for 
Incompressible SPH" where no gamma1 or gamma2 is used. The group of Universtiy Freiburg 
introduced these parameters in their pressure boundaries extension. This extension is not implemented since we developed volume maps, an implicit boundary representation, which allows for more accurate results.

i see that "delta" from the original paper of Akinci et al  is computed in the present code, thank you for clarifying that 
 i also read the volume maps original paper , it's a really great boundary handling method . 
the formulation from the tutorial for both the uniform and non-uniform boundary handling should work fine right ? is there an original paper describing that formulation ? or an open source code testing it ? if yes , i'd appreciate more documentation .  

> This is a small improvement in our code. By deriving the equations in a constraint form, we can find a factor where pressure mirroring is not required anymore. Instead of getting a local approximation at the boundary, we now get a locally exact result. However, it is hard to decribe the whole formulas here.

i think i kind of understand what you mean , is there a paper or some documentation that will clarify the point you are making ? 

Best Regards
