### ISSUE TITLE
How to mesh the particles after they have reached a steady state after emission? 

### ISSUE THREAD

**Issue by uljadberdica1000** [InteractiveComputerGraphics/SPlisHSPlasH#81]
I am trying to mesh the paticles using Zhu Bridson and Marcing Cubes but am unsure where to get the particle information so that I can generate a mesh. Is there any older commit that supports that?

**Comment by janbender** [comment]
We use a freeware tool called emPolygonizer for meshing which is based on marching cubes. However, the developer took the tool offline a few years ago since he don't want to spend more time on that. It is still a valuable tool and if you want to try you can find it in this archive:

https://web.archive.org/web/20160319035707/http://www.mootzoid.com/sites/default/files/dist/Mootzoid__Addons__emPolygonizer5.zip

Just use the command line tool to generate a mesh from the bgeo files that can be exported by SPlisHSPlasH.

**Comment by alt0216** [comment]
Where in the code is the bgeo file export located? I am trying to get the particles data while the simulation is running.

**Comment by janbender** [comment]
Just enable the Partio Export in the GUI or in the scene file as described here:

https://splishsplash.readthedocs.io/en/latest/file_format.html#export

**Comment by alt0216** [comment]
Thanks for replying. Is there a way to get the particles position without having to export via partio or vtk? I want to do meshing while splishsplash is running.

**Comment by janbender** [comment]
You could get them via the Python interface or in C++ from the FluidModel. Something like: 

```
Simulation *sim = Simulation::getCurrent();
for (unsigned int i = 0; i < sim->numberOfFluidModels(); i++)
{
	FluidModel *model = sim->getFluidModel(i);
	for (unsigned int i = 0; i < model->numActiveParticles(); i++)
	{
		Vector &x = model->getPosition(i);
		...
	}
}
```
