### ISSUE TITLE
Pressure solver on GPU?

### ISSUE THREAD

**Issue by Kulitorum** [InteractiveComputerGraphics/SPlisHSPlasH#91]
Is any work being done on this? - I build concrete 3D printers and I want to simulate the concrete flow with Splishsplash, but it's slow... (Intel 10850)

At the same time, my RTX 3090 is just sitting there, almost idle and it's hurting my heart.

Any beta version available or something?

**Comment by BluePrintRandom** [comment]
https://www.technologyreview.com/2020/10/30/1011435/ai-fourier-neural-network-cracks-navier-stokes-and-partial-differential-equations/?fbclid=IwAR1O4eMPDRNiQMeQUxNbYVNxi5q5AOKIBy_bboFzn0xL3FiWyVf7kHdneRM

this could really speed things up no?

**Comment by janbender** [comment]
A master student implemented two pressure solvers on the GPU: 

https://github.com/InteractiveComputerGraphics/SPlisHSPlasH/pull/53

However, we never merged that since there were again some issues and in the end the implementation was not faster than the CPU version. Maybe we will try again with a GPU implementation in the future but currently we don't have the capacity.

**Comment by Kulitorum** [comment]
On what CPU/GPU system were the CPU faster? - Hardware development on GPU seems to move fast thses days... (But then again, so does CPU development)

**Comment by BluePrintRandom** [comment]
https://www.technologyreview.com/2020/10/30/1011435/ai-fourier-neural-network-cracks-navier-stokes-and-partial-differential-equations/?fbclid=IwAR1O4eMPDRNiQMeQUxNbYVNxi5q5AOKIBy_bboFzn0xL3FiWyVf7kHdneRM

@kulitorum
