### ISSUE TITLE
Houdini import bgeo files error

### ISSUE THREAD

**Issue by haipengyuan** [InteractiveComputerGraphics/SPlisHSPlasH#93]
When I use Houdini to import the bgeo files exported by SPlisHSPlasH, there is an error. 
Error: Unable to read file "G:/partio/ParticleData_Fluid_1.bgeo".
Expected array object (near byte offset 22, line 1, column 23) Backend IO. 

I tried to export different scenes to bgeo files, but all have the same error in Houdini.
Windows 10, Houdini version: 18.5.351

In addition, I want to know what method you used to render the bego files or the VTK files into a video in your paper.
Thank you for your reply.

**Comment by janbender** [comment]
I think the problem is that we use an older Partio version in SPlisHSPlasH. The reason for that is that we use the freeware tool emPolygonizer for the surface reconstruction that only supports the old format. 

You can try to solve the problem by exchanging the Partio library in the extern folder by a newer version.

**Comment by janbender** [comment]
Concerning you second question. We render the particles using Maya and our plugin: 

https://github.com/InteractiveComputerGraphics/MayaPartioTools

**Comment by haipengyuan** [comment]
Thanks!

**Comment by Jinxi-Li** [comment]
I met your first problem too. Since I don't want to modify the extern of the source file, I tried the following easy way and it works. 
I built [Partio](https://github.com/wdas/partio) in python, and opened all the .bgeo files by partio.read then rewrite by partio.write. After that, all the new bgeo files could be opened by Houdini successfully.
